FROM n8nio/n8n:latest

WORKDIR /home/node/.n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=Arif@123
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
ENV PORT=5678

EXPOSE 5678

CMD ["n8n", "start"]
